### PR TITLE
Added changes for javadoc generation

### PR DESCRIPTION
**Pull request by s-aLman**

### CODE REVIEW

**Comment by s-aLman** [comment]
@andrii-bodnar I added some changes for documentation purposes. Can we create a new branch for gh-pages so that I can commit the generated doc files there?

**Comment by s-aLman** [comment]
Screenshot_20221105_152418
Screenshot_20221105_152444

**Comment by andrii-bodnar** [comment]
@s-aLman great, thank you! Could you please provide the command that generates the docs? 

We do not need to create the gh-pages branch and push the docs manually, it will be done via GH Actions

**Comment by s-aLman** [comment]
@andrii-bodnar Attaching some screenshots. We can add more annotations moving forward to improve the description. Let's setup the gh-actions workflow.

**Comment by s-aLman** [comment]
Sure, the command is simple gradle javadoc . That's it and the docs will get generated.

**Review by andrii-bodnar — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
@s-aLman just tried this but the workflow is failing - https://github.com/crowdin/crowdin-api-client-java/actions/runs/3399866147/jobs/5653897951

could you please check it?

**Comment by s-aLman** [comment]
@andrii-bodnar sure, I will check.

**Pull request merged**
