### PR TITLE
[ISSUE-46] - Fix bad named class & update type param for exportApprov…

### PR DESCRIPTION
**Pull request by Chikouni**
Related to #46

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
HI @Chikouni !

Thank you for pointing out, and congrats on your first contribution to this repo! :tada: 

There is one thing with this API method - different REQUEST BODY SCHEMA for **crowdin.com** and **Crowdin Enterprise**.

[Crowdin API v2 docs](https://support.crowdin.com/api/v2/#operation/api.projects.translations.exports.post)
[Crowdin Enterprise API v2 docs](https://support.crowdin.com/enterprise/api/#operation/api.projects.translations.exports.post)

first contains `exportApprovedOnly` field, the second contains `exportWithMinApprovalsCount` field.

`ExportProjectTranslationRequest` should work for both cases.

**Comment by Chikouni** [comment]
Hi @andrii-bodnar 
Yes but when i try to post https://api.crowdin.com/api/v2/projects/{project-id}/translations/exports with postman i have this error : 
                    {
                        "code": "notFound",
                        "message": "Field 'exportWithMinApprovalsCount' Not Found"
                    }

**Comment by andrii-bodnar** [comment]
@frombetelgeuse any ideas?

**Comment by Chikouni** [comment]
In the swagger we can see for the crowdin API v2 require the schema `ExportProjectTranslationRequest`
And in the swagger for the Crowdin Entreprise API v2 require the schema `EnterpriseTranslationExportForm`

In the client for java there is no class `EnterpriseTranslationExportForm`

**Comment by Chikouni** [comment]
@andrii-bodnar @frombetelgeuse 
I think the class `ExportProjectTranslationRequest` should be fixed with this PR and after you can create another class for `EnterpriseTranslationExportForm`
To keep the API contract "ISO"

**Comment by andrii-bodnar** [comment]
@Chikouni , ok, please fix the Unit test and PR will be merged

```
> Task :test

TranslationsApiTest > exportProjectTranslationTest() FAILED
    java.lang.AssertionError at TranslationsApiTest.java:137

175 tests completed, 1 failed

> Task :test FAILED

```

**Comment by Chikouni** [comment]
@andrii-bodnar 
It's done
Thanks 👍

**Comment by andrii-bodnar** [comment]
Thanks @Chikouni !

Is this issue blocks you and we need to release a new version with these changes ASAP or it can wait?

**Review by andrii-bodnar — APPROVED** [review]

**Comment by Chikouni** [comment]
@andrii-bodnar 
Now if it's possible because i'm blocked and i'm in agile sprint.
Can you release a new version asap please ? 

After that, i will be free to help you to fix some others classes because i saw some bugs

Thanks for you reactivity

**Comment by andrii-bodnar** [comment]
@Chikouni sure, I will release a new version in a few minutes

**Comment by andrii-bodnar** [comment]
@Chikouni, a new version (1.2.11) with the fix is already available

**Pull request merged**
