### PR TITLE
 Removed limit and offset parameters from listWorkflowSteps method

### PR DESCRIPTION
**Pull request by KatelynKunzmann**

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@KatelynKunzmann thanks a lot for your contribution!

Please rollback changes related to Gradle.

Also, some CI checks failed. See detailed log [here](https://dev.azure.com/crowdin/crowdin-api-client-java/_build/results?buildId=10580&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ea098990-53e4-52aa-5a84-5ead7c5f17f2) (don't pay attention to warnings, only error)

**Comment by KatelynKunzmann** [comment]
Apologies, this is my first time contributing. I will create a new pull request with a new fork that has the correct changes since rolling back did not work.

**Comment by KatelynKunzmann** [comment]
I noticed there was already a constructor for HttpRequestConfig that contains no parameters. So is this an appropriate change: 

```WorkflowStepResponseList workflowStepResponseList = this.httpClient.get(this.url + "/projects/" + projectId + "/workflow-steps", new HttpRequestConfig(), WorkflowStepResponseList.class);```

**Comment by andrii-bodnar** [comment]
@KatelynKunzmann, it should work if `HttpRequestConfig` can accept arguments as optional

**Comment by KatelynKunzmann** [comment]
Okay, unfortunately I already deleted and created a new fork before I saw your earlier comment so this pull request isn't linked up to it anymore. I have all the appropriate changes in the new fork. Again, my bad.

**Comment by andrii-bodnar** [comment]
@KatelynKunzmann hmm, it looks like it is still linked. Probably, GitHub somehow handles this

**Comment by KatelynKunzmann** [comment]
@andrii-bodnar I see it is still linked. I pushed my code but the PR has not updated with the new code, so maybe the deletion and recreation of the fork unlinked the PR from the fork. I'm currently researching a way to fix it, but it appears I might need to make a new PR.

**Comment by andrii-bodnar** [comment]
@KatelynKunzmann yes, it looks like a new PR is an easier way

**Comment by KatelynKunzmann** [comment]
Created the new PR, it looks like all checks have passed. Let me know if I need to change anything! Thank you for being patient with me.

**Pull request closed without merging**
